version: "3"

services:
  redis:
    image: redis
    restart: always
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    env_file:
      - db.env
  fpm:
    build:
        context: ./fpm
    volumes:
        - ./app/public:/app
    expose:
        - 9000
    links:
        - db
    environment:
        - "DB_HOST=db"
        - "DB_DATABASE=web"
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./app/public:/app
    links:
      - fpm
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8083:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: toor
        MYSQL_ROOT_PASSWORD: toor